config/routes.rb
Rails.application.routes.draw do
  resources :registered_applications

  devise_for :users, controllers: { registrations: "registrations"}

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

  namespace :api, defaults: { format: :json } do
  	 match '/events', to: 'events#preflight', via: [:options]
     resources :events, only: [:create]
   end
  
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :registered_application

	validates :registered_application, presence: true
  	validates :name, presence: true
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
	belongs_to :user
	has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:confirmable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :registered_applications
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
   skip_before_action :verify_authenticity_token

   before_action :set_access_control_headers

   def set_access_control_headers
     headers['Access-Control-Allow-Origin'] = '*'
     headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
     headers['Access-Control-Allow-Headers'] = 'Content-Type'
   end
 
   def create
   	registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

   	# Incorporated Guard Clause
   	return render json: { error: "Unregistered application"}, status: :unprocessable_entity if registered_application.nil?
   	@event = registered_application.events.build(event_params)
		if @event.save
   			render json: @event, status: :created
   		else 
   			render json: { errors: @event.errors }, status: :unprocessable_entity
   		end
   end

   def preflight
   	head 200
   end

   private

   def event_params
   	params.require(:event).permit(:name)
   end
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
  	registered_applications_path
  end

  	def configure_permitted_parameters
	   devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
	   devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:login, :email, :password, :remember_me) }
	   devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  	end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
   def index
   	@apps = RegisteredApplication.all
   end
 
   def show
   	@app = RegisteredApplication.find(params[:id])
   	@events = @app.events.group_by(&:name)
   end
 
   def new
  	@app = RegisteredApplication.new
   end
 
   def create
   	@app = RegisteredApplication.new(app_params)
   	@app.user = current_user
 
   	if @app.save
   		flash[:notice] = "Application was registered!"
   		redirect_to registered_applications_path
   	else
   		flash.now[:alert] = "There was an error saving the application. Please try again."
   		render :new
   	end
   end
 
   def destroy
   	 @app = RegisteredApplication.find(params[:id])
     #authorize @wiki
 
     if @app.destroy
       flash[:notice] = "\"#{@app.name}\" was deleted successfully."
      redirect_to registered_applications_path
     else
       flash.now[:alert] = "There was an error deleting your application. Try again."
       render :show
     end
  end

  private

  def app_params
    params.require(:registered_application).permit(:name, :url)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
 
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloc Analytics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
    <div class ="row">

<nav>

		<ul class="nav nav-tabs">
       <%= link_to "Home", welcome_index_path %> 
          <% if user_signed_in? %>
            <span class="navbar-text">Signed in as <strong><%= link_to current_user.email, user_session_path %> </strong></span>
          
              <%= link_to "Edit profile", edit_user_registration_path, class: 'navbar-link' %> 
            
         
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            
            
              <%= link_to "My Apps", registered_applications_path %>
           
          <% else %>
        <%= link_to "Sign Up", new_user_registration_path %>  |
            <%= link_to "Log In", new_user_session_path %>
        <% end %>
    </ul>
  </nav>

  </div>
		<%= yield %>
	</div>

</body>
</html>

app/views/registered_applications/destroy.html.erb
<h1>RegisteredApplications#destroy</h1>
<p>Find me in app/views/registered_applications/destroy.html.erb</p>

app/views/registered_applications/index.html.erb
<h1>Registered Applications</h1>
   <div class="row">
   	<div class="col-md-8">
   	<%= link_to "Register a New App", new_registered_application_path, class: 'btn-primary btn-sm' %>
   </div>
   </div>
<br/>

<div class="row">
  <div class="col-md-8">
    <% @apps.each do |app| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to app.name, registered_application_path(app) %>
          </h4>
          <small>
            <%= app.url %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/new.html.erb
 <h1>Register a new application</h1>
<br />
<div class="row">
  <div class="col-md-6">
    <%= form_for @app do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
      </div>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control', placeholder: "Enter application url" %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<div class="container">
	<div class="row">
		<%= link_to "Back to Main Page", registered_applications_path %>
			<h1>Application Name: <%= @app.name %></h1>
			<h4>URL: <%= @app.url %></h4>
	</div>
	<div class="row">
		<div class="col-6"
		<h3> Events </h3>
		  <%= pie_chart @app.events.group(:name).count %>
		</div>
		<div class="col-6">
		  <%= line_chart @app.events.group_by_week(:created_at, last: 4).count %>
		</div>
	</div>

		   
		<div class="btn-container">
		<div class="col-md-3 index-btn">
		      <%= link_to "delete", registered_application_path(@app), method: :delete, data: { confirm: "Are you sure you want to delete this application" } %>
		 </div>
		</div>

</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-sm-6">
      <h1>Bloc Analytics</h1>
      
        <% if user_signed_in? %>
          <h4>Welcome to Bloc Analytics, <%= current_user.email %>! </h4>
          	<%= link_to "My apps", registered_applications_path, class: 'btn-primary btn-lg' %>
        <% else %>
          <p>
            <h4>Register your application to begin gathering insights.</h4>

            <%= link_to "Sign Up", new_user_registration_path, class: 'btn-primary btn-lg'%>
            <%= link_to "Sign In", new_user_session_path, class: 'btn-success btn-lg' %>
          </p>
        <% end %>
    </div>
    <div class="col-sm-6">
      <img src="http://embed.ly/static/images/products/analytics_page_hero.png?v=72734" alt="Analytics">

    </div>
  </div>
  
</div>

  <div class="row">
    <div class="col-sm-4">
      <div class="thumbnail">
        <div class="caption">
          <h3>Free Plan</h3>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="thumbnail">
        <div class="caption">
          <h3>Total # of Registered Apps</h3>
         	<%= link_to "My apps", registered_applications_path, class: 'btn-primary btn-lg' %>
          @apps.count
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <div class="caption">
          <h3>Top Events</h3>
          <%= link_to "My apps", registered_applications_path, class: 'btn-primary btn-lg' %>
        </div>
      </div>
    </div>
  </div>